import type { Metadata } from 'next';
import { basier } from '@/utils/fonts';
import './globals.css';

import Announcement from './_components/Announcement';
import Navigation from './_components/Navigation';
import { Toaster } from 'react-hot-toast';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang='en'>
			<body className={basier.className}>
				<Announcement message='Programul nostru de sarbatori' />
				<Navigation />
				<div className='max-w-[1700px] mx-auto'>
					<div className='mx-4'>{children}</div>
				</div>
				<Toaster position='top-center' />
			</body>
		</html>
	);
}
