import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Announcement from './_components/Announcement';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang='en'>
			<body className={inter.className}>
				<Announcement message='Programul nostru de sarbatori' />
				{children}
			</body>
		</html>
	);
}
